#!/bin/bash

PWD=$(pwd)

### If old build folder exists, run cleanup
if [ -d "build" ]; then
    echo "Running cleanup script"
    ./scripts/clean
fi

### download node modules
echo "Downloading Node Modules"
cd framework
npm i
rm -f package-lock.json
cd ..

### Set up build folder
echo "Setting up build folder"
mkdir -p build/bin
mkdir -p build/www/js
mkdir -p build/cloud

# move server-side code into part
echo "Moving server-side code into build folder"
cp -rf framework/server/server.mjs build/bin
cp -rf framework/server/tools.mjs build/bin
cp -rf framework/node_modules build
cp -rf src/server/* build/bin
cp -rf src/all/* build/bin
cp -f scripts/run.sh build/bin/run
chmod +x build/bin/run

# move client-side code into part
echo "Moving client-side code into build folder"
cp -rf framework/web/* build/www/js
cp -rf www/* build/www
cp -rf src/web/* build/www/js
cp -rf src/all/* build/www/js

# move serverless code into part
echo "Moving serverless code into build folder"
# TODO: How to do this part effectively and generally?
cp -rf framework/server/lambda.mjs build/cloud
cp -rf framework/node_modules build/cloud
cp -rf src/core/* build/bin

### Deploy serverless code, if applicable
